"""Here are the genre descriptions for the novels in library:
    Action: Novels in this category are filled with excitement, fast-paced sequences, and intense physical or combat situations. Expect adrenaline-pumping adventures and heroic protagonists,
    Action - Martial Arts: These novels focus on martial arts as a central theme, with intricate fight scenes, martial arts philosophies, and often feature skilled martial artists as main characters,
    Action - Superhero: Dive into a world of extraordinary abilities and caped crusaders. Superheroes with superpowers or exceptional skills take center stage, battling villains and defending justice,
    Action - Spy: Experience the thrilling world of espionage, secret agents, and covert operations. These novels are full of intrigue, espionage, and suspense as spies navigate dangerous missions,
    Action - Disaster: Disaster novels center around catastrophic events, such as natural disasters, pandemics, or apocalyptic scenarios. Characters must survive and overcome the chaos,
    Action - Heist: Prepare for intricate and daring heists. These novels feature masterminds and their crews planning and executing high-stakes thefts and elaborate capers,
    Comedy: Expect laughter and humor in these novels. They are designed to amuse and entertain, often with witty dialogues and humorous situations,
    Comedy - Slapstick: Slapstick comedies rely on physical humor, exaggerated antics, and absurd situations. Get ready for hilarious mishaps and over-the-top gags,
    Comedy - Satire: Satirical comedies use humor to critique and comment on society, politics, or human behavior. They often employ irony and parody to make their points,
    Comedy - Dark Comedy: Dark comedies explore humor in morbid, uncomfortable, or taboo situations. They blend humor with darker themes and often challenge societal norms,
    Drama: These novels delve into deep and emotional storytelling, focusing on the complexities of human relationships, personal struggles, and life's challenges,
    Drama - Crime Drama: Crime dramas blend elements of drama with criminal investigations. Expect gripping plots centered around detectives, criminals, and mysteries to solve,
    Drama - Historical Drama: Immerse yourself in the past with historical dramas. These novels vividly depict historical events, figures, and settings while weaving engaging stories,
    Drama - Legal Drama: Legal dramas revolve around legal cases, courtroom battles, and the complexities of the justice system. They often feature lawyers and their clients,
    Drama - Melodrama: Melodramas are known for their heightened emotions and intense conflicts. Expect passionate characters, dramatic plot twists, and powerful storytelling,
    Drama - Psychological Drama: Dive into the minds of complex characters as they grapple with internal struggles, emotional challenges, and psychological conflicts,
    Horror: Horror novels aim to send shivers down your spine. They are filled with suspense, fear, and often supernatural elements that will keep you on the edge of your seat,
    Horror - Slasher: Slasher horror novels are characterized by serial killers hunting down their victims in gruesome and terrifying ways. Blood, suspense, and tension are prominent,
    Horror - Supernatural: Supernatural horror introduces paranormal elements like ghosts, demons, or otherworldly forces that haunt and terrify the characters,
    Horror - Psychological Horror: These novels delve into the psychological aspects of fear and horror, often blurring the line between reality and the characters' perceptions,
    Horror - Monster: Monster horror features terrifying creatures as the primary source of fear. These novels explore the terror of encountering monstrous beings,
    Science Fiction: Science fiction novels transport readers to future worlds, alternate realities, or speculative futures. They often explore technology, space, and scientific concepts,
    Science Fiction - Space Opera: Space operas are epic adventures set in the vastness of space. Expect intergalactic conflicts, starships, and grand-scale storytelling,
    Science Fiction - Cyberpunk: Cyberpunk novels delve into dystopian futures with advanced technology, hackers, and corporate control. They often have a gritty, urban feel,
    Science Fiction - Time Travel: Time travel science fiction explores the concept of traveling through time, with characters facing the consequences of altering the past or future,
    Science Fiction - Post-Apocalyptic: In post-apocalyptic novels, the world has suffered a catastrophic event, and characters must navigate the challenges of a changed, often desolate, landscape,
    Fantasy: Fantasy novels transport readers to magical realms with mythical creatures, epic quests, and extraordinary powers,
    Fantasy - High Fantasy: High fantasy novels feature intricate world-building, complex mythologies, and epic battles between forces of good and evil,
    Fantasy - Urban Fantasy: Urban fantasy blends the magical with the modern world, often set in urban settings where mythical creatures exist alongside ordinary humans,
    Fantasy - Fairy Tale: These novels draw inspiration from classic fairy tales, offering fresh perspectives on beloved stories and enchanting new tales,
    Fantasy - Sword and Sorcery: Sword and sorcery novels emphasize action-packed adventures, sword fighting, and magic in a medieval or fantastical setting,
    Romance: Romance novels focus on love, relationships, and emotional connections. They often follow the journey of characters as they fall in love,
    Romance - Historical Romance: Historical romances are set in the past, often featuring period-specific settings, costumes, and social norms,
    Romance - Contemporary Romance: Contemporary romances take place in modern times, exploring love and relationships in a contemporary context,
    Romance - Fantasy Romance: Fantasy romance combines the elements of fantasy with love stories, often featuring magical or supernatural elements that impact relationships,
    Romance - Teen Romance: Teen romances center around the romantic experiences and challenges faced by young adult characters,
    Romance - Romantic Drama: Romantic dramas emphasize emotional depth and conflict within relationships, often exploring themes of love and heartbreak,
    Mystery: Mystery novels revolve around solving puzzles, uncovering secrets, and solving crimes. Expect suspense and intrigue as characters investigate,
    Mystery - Detective: Detective mysteries feature skilled investigators solving crimes through deductive reasoning and clever sleuthing,
    Mystery - Whodunit: Whodunit mysteries keep readers guessing about the identity of the culprit until the very end, with unexpected plot twists,
    Mystery - Noir: Noir mysteries have a dark and cynical tone, often set in gritty urban environments with morally ambiguous characters,
    Mystery - Legal Thriller: Legal thrillers combine the legal and mystery genres, focusing on courtroom dramas and legal investigations,
    Mystery - Police Procedural: Police procedural mysteries follow the step-by-step investigative process of law enforcement as they solve crimes,
    Thriller: Thriller novels are known for their suspenseful and gripping plots. They often involve danger, intrigue, and high-stakes situations,
    Thriller - Psychological Thriller: Psychological thrillers play with the minds of characters and readers, exploring psychological tension and manipulation,
    Thriller - Crime Thriller: Crime thrillers feature criminal activities, investigations, and suspenseful plots centered around criminals and law enforcement,
    Thriller - Political Thriller: Political thrillers delve into political intrigue, espionage, and power struggles on a national or international scale,
    Thriller - Techno Thriller: Techno thrillers combine technology and suspense, often featuring high-tech espionage, hacking, and cyber threats,
    Thriller - Conspiracy Thriller: Conspiracy thrillers unravel complex conspiracies, often involving government secrets, cover-ups, and hidden agendas,
    Animation: Animated novels bring stories to life through illustrated or animated visuals
    Adventure: Adventure novels are characterized by their thrilling and often perilous journeys and escapades. They typically feature protagonists who embark on exciting quests, exploration, or challenges, often in exotic or dangerous settings. These stories are known for their high levels of excitement, action, and a sense of discovery. Adventure novels can span a wide range of sub-genres, from swashbuckling pirate tales to expeditions into uncharted territories,
    Crime: Crime novels, also known as detective or mystery novels, revolve around the investigation and resolution of criminal activities. These stories feature detectives, investigators, or amateur sleuths who work to solve crimes such as murders, thefts, or other illicit activities. Crime novels often delve into the psychological aspects of both the criminals and the investigators, creating a sense of suspense and intrigue,
    Family: Family novels focus on the dynamics and relationships within a family unit. They explore themes related to family life, love, conflicts, and the challenges faced by various family members. These novels often provide insights into the complexities of human connections and the evolution of family bonds over time. Family novels can encompass a wide range of emotions and experiences, from heartwarming tales of love and reconciliation to stories of dysfunction and discord,
    Musical: Musical novels bring the world of music and performance to life through storytelling. These novels often center around musicians, composers, or individuals with a deep passion for music. They may explore the creative process, the struggles and triumphs of artists, and the emotional power of music to connect people. Musical novels can resonate with readers who appreciate both literature and the artistry of music,
    War: War novels depict the experiences of individuals and communities during times of armed conflict. They often explore the profound impact of war on both soldiers and civilians, delving into themes of bravery, sacrifice, trauma, and the moral complexities of warfare. These novels can be set in various historical periods and settings, shedding light on the human condition in times of crisis,
    Western: Western novels are typically set in the American Old West during the 19th century. They feature elements such as cowboys, outlaws, gunfights, and rugged landscapes. These stories often explore themes of rugged individualism, justice, and the clash between civilization and the wilderness. Western novels offer readers a glimpse into a bygone era characterized by adventure, frontier life, and a code of honor
    """